// @generated by esop-cfggen; do not edit.
use esop_product_config::{
Cia402AxisCommandPolicy, Command, DomainConfig, DomainDatagramSpec, OperatingMode,
PdoDirection, PdoRegistrationRequest, ProcBufDimensions, ProcBufLayoutDescriptor,
ProductAxisConfig, ProductDatagramConfig, ProductDomainConfig, ProductMetadata,
ProductPdoConfig, ProductSlaveConfig, ProductSlaveKind, SlaveIdentity,
StaticProductConfig,
};

static PRODUCT_PDOS: [ProductPdoConfig; 16] = [
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 0, request: PdoRegistrationRequest::new(0, 0x6040, 0, PdoDirection::Rx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 16, request: PdoRegistrationRequest::new(0, 0x6060, 0, PdoDirection::Rx, 8, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 24, request: PdoRegistrationRequest::new(0, 0x607a, 0, PdoDirection::Rx, 32, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 56, request: PdoRegistrationRequest::new(1, 0x6040, 0, PdoDirection::Rx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 72, request: PdoRegistrationRequest::new(1, 0x6060, 0, PdoDirection::Rx, 8, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1600, sync_manager: 2, bit_offset: 80, request: PdoRegistrationRequest::new(1, 0x607a, 0, PdoDirection::Rx, 32, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 112, request: PdoRegistrationRequest::new(0, 0x6041, 0, PdoDirection::Tx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 128, request: PdoRegistrationRequest::new(0, 0x6061, 0, PdoDirection::Tx, 8, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 136, request: PdoRegistrationRequest::new(0, 0x603f, 0, PdoDirection::Tx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 152, request: PdoRegistrationRequest::new(0, 0x6064, 0, PdoDirection::Tx, 32, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 184, request: PdoRegistrationRequest::new(1, 0x6041, 0, PdoDirection::Tx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 200, request: PdoRegistrationRequest::new(1, 0x6061, 0, PdoDirection::Tx, 8, true) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 208, request: PdoRegistrationRequest::new(1, 0x603f, 0, PdoDirection::Tx, 16, false) },
    ProductPdoConfig { domain_id: 0, assignment_index: 0x1a00, sync_manager: 3, bit_offset: 224, request: PdoRegistrationRequest::new(1, 0x6064, 0, PdoDirection::Tx, 32, true) },
    ProductPdoConfig { domain_id: 1, assignment_index: 0x1601, sync_manager: 2, bit_offset: 0, request: PdoRegistrationRequest::new(2, 0x7000, 1, PdoDirection::Rx, 16, false) },
    ProductPdoConfig { domain_id: 1, assignment_index: 0x1a01, sync_manager: 3, bit_offset: 16, request: PdoRegistrationRequest::new(2, 0x6000, 1, PdoDirection::Tx, 16, false) },
];

static PRODUCT_DATAGRAMS: [ProductDatagramConfig; 4] = [
    ProductDatagramConfig { domain_id: 0, spec: DomainDatagramSpec::new(Command::Lwr, 0, 0x00001000, 0, 14, 2, false) },
    ProductDatagramConfig { domain_id: 0, spec: DomainDatagramSpec::new(Command::Lrd, 1, 0x0000100e, 14, 18, 2, true) },
    ProductDatagramConfig { domain_id: 1, spec: DomainDatagramSpec::new(Command::Lwr, 2, 0x00001100, 0, 2, 1, false) },
    ProductDatagramConfig { domain_id: 1, spec: DomainDatagramSpec::new(Command::Lrd, 3, 0x00001102, 2, 2, 1, true) },
];

#[allow(clippy::approx_constant)]
pub static PRODUCT_CONFIG: StaticProductConfig<'static, 3, 2, 2> = StaticProductConfig {
    metadata: ProductMetadata {
        schema_version: "esop.product-runtime.v1",
        product_name: "ESOP dual-axis simulator",
        config_sha256: [0x49, 0x26, 0x96, 0xaa, 0xb6, 0x8a, 0x69, 0x7d, 0xaf, 0xc5, 0xe1, 0xcf, 0xd6, 0xd0, 0xc6, 0x0b, 0x5d, 0x17, 0x1e, 0x7e, 0x74, 0x57, 0xa3, 0xa2, 0x2c, 0x65, 0x28, 0x93, 0x6a, 0xc0, 0x1c, 0x27],
        robot_id: 0x000000000000e502,
        policy_version: 1,
        base_period_ns: 1000000,
        deadline_ns: 800000,
    },
    procbuf_layout: ProcBufLayoutDescriptor { dimensions: ProcBufDimensions { axes: 2, io_channels: 16, domains: 2, event_capacity: 64 }, header_bytes: 48, command_page_bytes: 272, state_page_bytes: 728, event_record_bytes: 32, event_ring_bytes: 2064, region_bytes: 4144, layout_hash: 0x9f41a7c67a7a6376 },
    slaves: [
        ProductSlaveConfig { name: "drive_left", position: 0, station_address: 0x1001, domain_id: 0, kind: ProductSlaveKind::Cia402Drive, identity: SlaveIdentity { vendor_id: 0x0000e500, product_code: 0x00004020, revision: 0x00000001, serial: 0x00000001 } },
        ProductSlaveConfig { name: "drive_right", position: 1, station_address: 0x1002, domain_id: 0, kind: ProductSlaveKind::Cia402Drive, identity: SlaveIdentity { vendor_id: 0x0000e500, product_code: 0x00004020, revision: 0x00000001, serial: 0x00000002 } },
        ProductSlaveConfig { name: "io_block", position: 2, station_address: 0x1003, domain_id: 1, kind: ProductSlaveKind::EthercatIo, identity: SlaveIdentity { vendor_id: 0x0000e500, product_code: 0x00007010, revision: 0x00000001, serial: 0x00000000 } },
    ],
    domains: [
        ProductDomainConfig { name: "motion", config: DomainConfig::new(0, 0x00001000, 0, 32, 1, 0), expected_pdo_count: 14, expected_datagram_count: 2, expected_wkc: 4, input_expected_wkc: 2 },
        ProductDomainConfig { name: "io", config: DomainConfig::new(1, 0x00001100, 64, 4, 4, 0), expected_pdo_count: 2, expected_datagram_count: 2, expected_wkc: 2, input_expected_wkc: 1 },
    ],
    pdos: &PRODUCT_PDOS,
    datagrams: &PRODUCT_DATAGRAMS,
    axes: [
        ProductAxisConfig { name: "left_joint", index: 0, slave_position: 0, mode: OperatingMode::Csp, policy: Cia402AxisCommandPolicy { position_units_per_radian: 100000.0, velocity_units_per_radian_per_second: 1000.0, torque_units_per_newton_metre: 100.0, position_offset: 0, min_position_radians: -3.141592653589793, max_position_radians: 3.141592653589793, max_velocity_radians_per_second: 10.0, max_torque_newton_metres: 100.0, max_position_step_radians: 0.02 } },
        ProductAxisConfig { name: "right_joint", index: 1, slave_position: 1, mode: OperatingMode::Csp, policy: Cia402AxisCommandPolicy { position_units_per_radian: -100000.0, velocity_units_per_radian_per_second: -1000.0, torque_units_per_newton_metre: -100.0, position_offset: 0, min_position_radians: -3.141592653589793, max_position_radians: 3.141592653589793, max_velocity_radians_per_second: 10.0, max_torque_newton_metres: 100.0, max_position_step_radians: 0.02 } },
    ],
};
